//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public string GameTitles { get; set; }
        public int GenreID { get; set; }
        public int PublisherID { get; set; }
        public int StockID { get; set; }
        public int ConsoleID { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> TotalSales { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual Console Console { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual StockStatus StockStatus { get; set; }
    }
}
